dist: xenial

language: php

matrix:
  include:
    - php: 7.0
    - php: 7.0
      env: COMPOSER_FLAGS='--prefer-lowest'
    - php: 7.1
    - php: 7.1
      env: COMPOSER_FLAGS='--prefer-lowest'
    - php: 7.2
    - php: 7.2
      env: COMPOSER_FLAGS='--prefer-lowest'
    - php: 7.3
    - php: 7.3
      env: COMPOSER_FLAGS='--prefer-lowest'
    - php: 7.4
      env: ANALYSIS=1
    - php: 7.4
      env: COMPOSER_FLAGS='--prefer-lowest'
    - php: nightly
#Added power jobs
    - php: 7.0
      arch: ppc64le
    - php: 7.0
      arch: ppc64le
      env: COMPOSER_FLAGS='--prefer-lowest'
    - php: 7.1
      arch: ppc64le
    - php: 7.1
      arch: ppc64le
      env: COMPOSER_FLAGS='--prefer-lowest'
    - php: 7.2
      arch: ppc64le
    - php: 7.2
      arch: ppc64le
      env: COMPOSER_FLAGS='--prefer-lowest'
    - php: 7.3
      arch: ppc64le
    - php: 7.3
      arch: ppc64le
      env: COMPOSER_FLAGS='--prefer-lowest'
    - php: 7.4
      arch: ppc64le
      env: ANALYSIS=1
    - php: 7.4
      arch: ppc64le
      env: COMPOSER_FLAGS='--prefer-lowest'
    - php: nightly 
      arch: ppc64le     
  allow_failures:
    - php: nightly
  fast_finish: true

cache:
  directories:
    - $HOME/.composer

before_install:
  - composer global outdated --strict hirak/prestissimo || composer global require hirak/prestissimo

install:
  - COMPOSER_MEMORY_LIMIT=-1 travis_retry composer update $COMPOSER_FLAGS --no-suggest
  - if [ $ANALYSIS == 1 ]; then travis_retry composer update --working-dir=./dev-tools --no-suggest; fi

script:
  - vendor/bin/phpunit --verbose --coverage-clover=coverage.clover
  - if [ $ANALYSIS == 1 ]; then ./dev-tools/analyse.sh || travis_terminate 1; fi

after_script:
  - sh -c 'if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then wget https://scrutinizer-ci.com/ocular.phar && php ocular.phar code-coverage:upload --format=php-clover coverage.clover; fi;'

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/fc8ccb3e96abeb0fdc95
    on_success: change
    on_failure: always
    on_start: never
